Vagrant.configure("2") do |config|

  config.vm.define "clusterNode" do |node|
    node.vm.box = "generic/ubuntu1804"
    node.vm.disk :disk, size: "150GB", primary: true
    node.vm.disk :disk, size: "50GB", name: "rabbitmqvol"
    node.vm.disk :disk, size: "50GB", name: "cockroachdbvol"
    node.vm.network :public_network, bridge: "Hyper-V Virtual Ethernet Adapter #2", ip: "192.168.0.11"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 6
    end
	
    node.vm.provision :shell, path: "bootstrap-node.sh", reboot: true
  end
  
  config.vm.define "clusterController" do |controller|
    controller.vm.hostname = "cluster.controller"
    controller.vm.box = "generic/ubuntu1804"
    controller.vm.disk :disk, size: "75GB", primary: true
    controller.vm.network :public_network, bridge: "Hyper-V Virtual Ethernet Adapter #2", ip: "192.168.0.12"
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    controller.vm.provision :shell, path: "bootstrap-ssh-1.sh"
    controller.vm.provision :shell, path: "bootstrap-ssh-2.sh", privileged: false
    controller.vm.provision :shell, path: "bootstrap-controller.sh"
  end

end
