Vagrant.configure("2") do |config|

  config.vm.define "clusterNode" do |node|
    node.vm.box = "generic/ubuntu1804"
    node.vm.disk :disk, size: "150GB", primary: true
    node.vm.disk :disk, size: "50GB", name: "rabbitmqvol"
    node.vm.disk :disk, size: "50GB", name: "cockroachdbvol"
    node.vm.network :public_network, bridge: "Hyper-V Virtual Ethernet Adapter #2", ip: "192.168.0.11"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 6
    end
	
    node.vm.provision :shell, path: "bootstrap-node.sh", reboot: true
  end

end
