Vagrant.configure("2") do |config|

  config.vm.define "clusterNode" do |node|
    node.vm.box = "ubuntu/trusty64"
    node.vm.disk :disk, size: "75GB", primary: true
    node.vm.disk :disk, size: "75GB", name: "kubevol"
    node.vm.network "private_network", ip: "192.168.0.11"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
	
	controller.vm.provision "shell", path: "bootstrap.sh"
  end
end
