Vagrant.configure("2") do |config|

  config.vm.define "clusterController" do |controller|
    controller.vm.hostname = "cluster.controller"
    controller.vm.box = "ubuntu/trusty64"
    controller.vm.disk :disk, size: "75GB", primary: true
    controller.vm.network "private_network", ip: "192.168.0.100"
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    controller.vm.provision "shell", path: "bootstrap.sh"
  end
end
